meta_title: "Ask EU"
meta_title_2: "Where the EU & its Citizens find solutions"
meta_description: "Crowdsourcing Help for feedbacks and reports"
meta_image: "AskEU_LOGO.png" # should exist in `app/assets/images/`
